spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true
      path: /h2-console
mybatis:
  type-aliases-package: com.example.demo.entity
  type-handlers-package: com.example.demo.typeHandler
  configuration:
    map-underscore-to-camel-case: true